sudo: required
language: generic
group: edge
script:
 - sudo apt-get install cabextract -y
 - sh download.sh && rm *.sh
before_deploy:
 - zip -9lr Dogfood_DevMain *
deploy:
  skip_cleanup: true
  edge: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
   - Dogfood_DevMain.zip
