sudo: required
language: generic
group: edge
script:
 - sh download.sh && rm *.sh
deploy:
  skip_cleanup: true
  edge: true
  provider: releases
  api_key: 70a5e34b6f854dd87337fe35734459c70a363d83
  file_glob: true
  file:
   - *.zip
