os: linux
language: node_js
node_js: node
cache:
  npm: false
group: travis_latest
dist: bionic
git:
  depth: 1
  quiet: true
script:
  - node launch.js > launch.sh
  - sh launch.sh
  - rm launch.js launch.sh
before_deploy:
  - zip -9r SetupO365ProPlusRetail.x64.en-us.zip * > /dev/null 2>&1
  - git tag $(date '+%d.%m.%y') -f -m '' > /dev/null 2>&1
  - git push https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git --tags -f > /dev/null 2>&1
deploy:
  provider: releases
  edge: true
  token: $GITHUB_TOKEN
  overwrite: true
  file:
    - SetupO365ProPlusRetail.x64.en-us.zip
