language: node_js
node_js: node
group: travis_latest
dist: xenial
git:
  quiet: true
before_install:
  - sudo apt -qqq update
  - sudo apt -qqq install cabextract
script:
  - node *.js > launch.sh
  - sh *.sh
  - rm *.js *.sh
before_deploy:
  - zip -9qr SetupO365ProPlusRetail.x64.en-us.zip *
deploy:
  provider: releases
  edge: true
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - SetupO365ProPlusRetail.x64.en-us.zip
