sudo: required
language: generic
group: edge
script:
 - sh download.sh && rm *.sh
before_deploy:
 - zip -9lr Dogfood_DevMain *
 - split -b 1536M Dogfood_DevMain.zip
 - rm Dogfood_DevMain.zip
deploy:
  skip_cleanup: true
  edge: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
   - xaa
   - xab
   - xac
